version: "3"
services:
  engine:
    container_name: ttt-engine
    build: ./engine
    command: stack run --allow-different-user
    ports:
      - 3001:3000
    volumes:
      - ./engine:/opt/app
  client:
    container_name: ttt-client
    build: ./client
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/opt/server
